// <auto-generated />
namespace BaskifyClient.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class contactPageModelReqs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contactPageModelReqs));
        
        string IMigrationMetadata.Id
        {
            get { return "202007261713369_contactPageModelReqs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
