// <auto-generated />
namespace baskifyCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class basketContentString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(basketContentString));
        
        string IMigrationMetadata.Id
        {
            get { return "202005040754431_basketContentString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
